# Site settings
title: System-on-Chip Design & Verification
author:
  name: Fergal McNamara
  email: g00180082@atu.ie
description: "VGA Driver Design blog."

# Build settings
remote_theme: jekyll/minima
